In [4]:
import numpy as np
a=np.array([1,2,3,4])
np.array([1,2,3])

array([1, 2, 3])

In [7]:
import numpy as np
a=np.array([1,2,3,4])
a+2

array([3, 4, 5, 6])

In [8]:
import numpy as np
a=np.array([1,2,3,4])
a/2

array([0.5, 1. , 1.5, 2. ])

In [9]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [10]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a.shape
b.shape

(4,)

In [22]:
import numpy as np
m=np.array([[1,2,3],
           [4,5,6]])
m.ndim
m.shape
m.size
print(m.ndim)
print(m.shape)
print(m.size)

2
(2, 3)
6


In [17]:
import numpy as np
m=np.array([[1,2,3],
           [4,5,6]])
m[1,2]

6