In [1]:
import numpy as np
a=np.array([1,2,3])
print(a[0])
print(a[1])
print(a[2])

1
2
3


In [3]:
import numpy as np
a=np.array([[1,2,3],
           [4,5,6]])
print(a[0,0])
print(a[0,1])
print(a[0,2])
print(a[1,0])
print(a[1,1])
print(a[1,2])      

1
2
3
4
5
6


In [5]:
import numpy as np
a=np.array([3,2,1,5,4])
print(a[0:4])
print(a[1:4])
print(a[2:4])
print(a[3:4])
print(a[4:4])

[3 2 1 5]
[2 1 5]
[1 5]
[5]
[]


In [6]:
import numpy as np
a=np.array([3,2,1,5,4])
print(a[:4])

[3 2 1 5]


In [7]:
import numpy as np
a=np.array([3,2,1,5,4])
print(a[2:])

[1 5 4]


In [8]:
import numpy as np
a=np.array([3,2,1,5,4])
print(a[::2])

[3 1 4]


In [13]:
import numpy as np
a=np.array([[1,3,4],
            [2,7,9],
            [1,5,9]])
print(a[0:2,1:2])
print(a[1:2,0:2])
print(a[0:2,2:1])
print(a[0:2,1:2])

[[3]
 [7]]
[[2 7]]
[]
[[3]
 [7]]


In [14]:
import numpy as np
a=np.array([[1,3,4],
            [2,7,9],
            [1,5,9]])
print(a[:,1])

[3 7 5]


In [16]:
import numpy as np
a=np.array([[1,3,4],
            [2,7,9],
            [1,5,9]])
print(a[1,:])

[2 7 9]
