In [6]:
import numpy as np
a=np.array([[1,2,4],
           [1,7,9],
            [2,7,2]])
a.sum()
a.mean()
a.max()
a.min()
print(a.sum())
print(a.mean())
print(a.max())
print(a.min())

35
3.888888888888889
9
1


In [11]:
import numpy as np
a=np.array([[1,2,4],
           [1,7,9],
            [2,7,2]])
a.sum(axis=0)
a.mean(axis=0)
a.max(axis=0)
a.min(axis=0)
print(a.sum(axis=0))
print(a.mean(axis=0))
print(a.max(axis=0))
print(a.min(axis=0))

[ 4 16 15]
[1.33333333 5.33333333 5.        ]
[2 7 9]
[1 2 2]


In [1]:
import numpy as np
a=np.array([[1,2,4],
           [1,7,9],
            [2,7,2]])
print(a[a>2])

[4 7 9 7]


In [10]:
import numpy as np
a=np.array([[1,2,4],
           [1,7,9],
            [2,7,2]])
a.reshape(1,9)
a.reshape(3,3)
a.reshape(3,-1)
print(a.reshape(1,9))
print(a.reshape(9,1))
print(a.reshape(3,-1))

[[1 2 4 1 7 9 2 7 2]]
[[1]
 [2]
 [4]
 [1]
 [7]
 [9]
 [2]
 [7]
 [2]]
[[1 2 4]
 [1 7 9]
 [2 7 2]]


In [11]:
import numpy as np
a=np.array([[1,2,4],
           [1,7,9],
            [2,7,2]])
print(a.dtype)

int32


In [13]:
import numpy as np
a=np.array([[1,2,4],
           [1,7,9],
            [2,7,2]])
a_float=a.astype(float)
print(a_float.dtype)

float64
